KaziYangu/urls.py
from django.contrib import admin, sitemaps
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, url
from profiles.views import CustomPasswordChangeView
from django.contrib.sitemaps.views import sitemap
from jobs.sitemap import JobSitemap


sitemaps={
    'jobs': JobSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/',include('jobs.urls')),
    path('applications/',include('applications.urls')),
    path("accounts/password/change/", CustomPasswordChangeView.as_view(), name="account_password_change"),
    path('accounts/', include('allauth.urls')),
    path('ratings/',include('star_ratings.urls',namespace="ratings")),
    path('profiles/', include('profiles.urls')),
    path('blogs/', include('blogs.urls')),
    path('', include('pages.urls')),
    
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404'
handler500 = 'pages.views.error_500'

jobs/urls.py
from django.urls import path
from .import views
# from django_filters.views import FilterView
from .views import DeleteJobView, JobDetailView,UserView ,JobView, AddJobView,cancel,done_job,approve_application,UpdateJobView,JobApplicationsView,JobApplicationsView,MyJobsView,TagView,pdf,get_done_page


urlpatterns = [
    path('',JobView.as_view(), name="jobs"),
    path('my_jobs',MyJobsView.as_view(),name='my_jobs'),
    path('<slug>',JobDetailView.as_view(),name='job_details'),
    path('add_job/',AddJobView.as_view(),name='add_job'),
    path('edit/<slug>',UpdateJobView.as_view(),name="update_job"),
    path('delete/<slug>',DeleteJobView.as_view(),name="delete_job"),
    path('this_job_applications/<slug>',JobApplicationsView.as_view(),name="this_job_applications"),
    path('<application_uuid>/approvekkkkkkkkk',approve_application,name="approve"),
    path('<application_uuid>/donegggggggggg',done_job,name='done'),
    path('<application_uuid>/done44444444444',get_done_page,name='done-page'),
    path('<application_uuid>/cancel',cancel,name='cancel_job'),
    path('tags/<slug>/',TagView,name="tags"),
    path('jobs_by/<username>/',UserView,name="jobs_by"),
    # path('LLLL/pdfhhhj',get_invoice,name="pdf"),
    path('<application_uuid>/ppp/pdf',pdf,name="get-invoice"),
    # path('search/',views.search,name='search'),  
    # path('applicant/<slug>/applicant',ApplicantProfileView.as_view(),name="applicant"),

    # path('<slug>/applications',JobApplicationView.as_view(),name="job_applications")
    # path('this_job_applications/<slug>/approve', ApproveApplication.as_view(),name="approve"),
    # path('my_jobs/<str:username>',MyJobsView.as_view(),name='my_jobs'),
    # path('my_jobs',MyJobsView.as_view(),name='my_jobs'),

]

jobs/models.py
from msilib.schema import LockPermissions
from turtle import title
from django.db import models
from autoslug import AutoSlugField
from django.conf import settings
from  ckeditor.fields import RichTextField
from django.db.models.deletion import CASCADE
from django.urls import reverse
import uuid,datetime
from PIL import Image
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.contrib.postgres.indexes import GinIndex
from pkg_resources import to_filename
from django.template.defaultfilters import slugify
from prompt_toolkit import application
import random,string

class Category(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,editable=False,on_delete=models.CASCADE,null=False)
    name = models.CharField(max_length = 255)
    slug = AutoSlugField(populate_from='name', unique=True)
    description =RichTextField()
    created_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("tags",kwargs={'slug':self.slug})

    def save(self,*args, **kwargs):
        self.slug= slugify(self.name)
        return super(Category,self).save(*args, **kwargs)

    # def get_absolute_url(self):
    #     return reverse("artist_category",kwargs={'slug':self.slug})

class Tag(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,editable=False,on_delete=models.CASCADE,null=False,related_name='job_tag_user')
    category=models.ForeignKey(Category,on_delete=models.CASCADE,related_name='blog_category_tag')  
    name = models.CharField(max_length = 255)
    slug = AutoSlugField(populate_from='name', unique=True)
    description =RichTextField()
    created_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("tags",kwargs={'slug':self.slug})
    def save(self,*args, **kwargs):
        self.slug= slugify(self.name)
        return super(Tag,self).save(*args, **kwargs)

def random_string_generator(size=10,chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def unique_job_id_generator(instance):
    
    new_job_id =random_string_generator().upper()
    Klass = instance.__class__
    qs_exists =Klass.objects.filter(job_id =new_job_id).exists()
    if qs_exists:
        return unique_job_id_generator(instance)
    return new_job_id

# Create your models here.
class Job(models.Model):
    Mombasa = 'Mombasa'
    Kwale= 'Kwale'
    Kilifi= 'Kilifi'
    TanaRiver= 'Tana River'
    Lamu= 'Lamu'
    TaitaTaveta= 'Taita-Taveta'
    Garissa ='Garissa'
    Wajir= 'Wajir'
    Mandera= 'Mandera'
    Marsabit= 'Marsabit'
    Isiolo= 'Isiolo'
    MERU= 'MERU'
    TharakaNithi= 'Tharaka-Nithi'
    Embu= 'Embu'
    Kitui ='Kitui'
    Machakos= 'Machakos'
    Makueni= 'Makueni'
    Nyandarua= 'Nyandarua'
    Nyeri= 'Nyeri'
    Kirinyaga='Kirinyaga'
    Muranga="Muranga"
    Kiambu= 'Kiambu'
    Turkana ='Turkana'
    WestPokot='West Pokot'
    Samburu= 'Samburu'
    TransNzoia ='Trans Nzoia'
    UasinGishu= 'Uasin Gishu'
    ElgeyoMarakwet= 'Elgeyo-Marakwet'
    Nandi ='Nandi'
    Baringo= 'Baringo'
    Laikipia ='Laikipia'
    Nakuru= 'Nakuru'
    Narok= 'Narok'
    Kajiado= 'Kajiado'
    Kericho= 'Kericho'
    Bomet= 'Bomet'
    Kakamega ='Kakamega'
    Vihiga= 'Vihiga'
    Bungoma= 'Bungoma'
    Busia= 'Busia'
    Siaya= 'Siaya'
    Kisumu ='Kisumu'
    HomaBay= 'Homa Bay'
    Migori= 'Migori'
    Kisii= 'Kisii'
    Nyamira= 'Nyamira'
    Nairobi= 'Nairobi'

    county_choice= [
        (Mombasa, 'Mombasa'),
        (Kwale, 'Kwale'),
        (Kilifi, 'Kilifi'),
        (TanaRiver, 'Tana River'),
        (Lamu, 'Lamu'),
        (TaitaTaveta, 'Taita-Taveta'),
        (Garissa ,'Garissa'),
        (Wajir, 'Wajir'),
        (Mandera, 'Mandera'),
        (Marsabit, 'Marsabit'),
        (Isiolo, 'Isiolo'),
        (MERU, 'Meru'),
        (TharakaNithi, 'Tharaka-Nithi'),
        (Embu, 'Embu'),
        (Kitui ,'Kitui'),
        (Machakos, 'Machakos'),
        (Makueni, 'Makueni'),
        (Nyandarua, 'Nyandarua'),
        (Nyeri, 'Nyeri'),
        (Kirinyaga,'Kirinyaga'),
        (Muranga,"Murang'a"),
        (Kiambu, 'Kiambu'),
        (Turkana ,'Turkana'),
        (WestPokot,' West Pokot'),
        (Samburu, 'Samburu'),
        (TransNzoia ,'Trans Nzoia'),
        (UasinGishu, 'Uasin Gishu'),
        (ElgeyoMarakwet, 'Elgeyo-Marakwet'),
        (Nandi ,'Nandi'),
        (Baringo, 'Baringo'),
        (Laikipia ,'Laikipia'),
        (Nakuru, 'Nakuru'),
        (Narok, 'Narok'),
        (Kajiado, 'Kajiado'),
        (Kericho, 'Kericho'),
        (Bomet, 'Bomet'),
        (Kakamega ,'Kakamega'),
        (Vihiga, 'Vihiga'),
        (Bungoma, 'Bungoma'),
        (Busia, 'Busia'),
        (Siaya, 'Siaya'),
        (Kisumu ,'Kisumu'),
        (HomaBay, 'Homa Bay'),
        (Migori, 'Migori'),
        (Kisii, 'Kisii'),
        (Nyamira, 'Nyamira'),
        (Nairobi, 'Nairobi'),
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=False)
    job_id = models.CharField(blank=True,max_length=30)
    title = models.CharField(max_length=250)
    slug = AutoSlugField(populate_from='title', unique=True)
    tag = models.ForeignKey(Tag,verbose_name="Tag",on_delete=models.CASCADE)
    description = RichTextField()
    application_deadline = models.DateTimeField(auto_now_add=False)
    job_done_date = models.DateTimeField(auto_now_add=False)
    county =models.CharField( choices=county_choice, max_length=20,  default=Nairobi)
    location= models.CharField(max_length=250)
    address = models.CharField(max_length=250)   
    status = models.CharField(max_length=250,blank=True,null=True,default="waiting")
    is_featured = models.BooleanField(default=False)
    is_cancelled = models.BooleanField(default=False)
    image =models.ImageField(upload_to='jobs/job_images/',default='jobs/job_images/jobs.jpg',blank=True,null=True)
    video =models.FileField(upload_to='jobs/job_videos/',blank=True,null=True)
    created_date = models.DateTimeField(auto_now_add=True)



    class Meta:
        indexes = [
            GinIndex(name='NewGinIndex',fields=['title',],opclasses=['gin_trgm_ops'])
            ]
 
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("job_details", kwargs={"slug": self.slug})
        
    def get_related_job_by_tag(self):
        return Job.objects.filter(application_deadline__gte=datetime.datetime.now(),status='waiting',tag_id =self.tag_id).exclude(pk=self.pk).order_by('-created_date')[:8]
   
    @property 
    def photo_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url 
    def save(self,*args, **kwargs):
        self.slug= slugify(self.title)
        return super(Job,self).save(*args, **kwargs)
    @property 
    def video_url(self):
        if self.video and hasattr(self.video, 'url'):
            return self.video.url 

def pre_save_job_id(sender,instance,*args,**kwargs):
        if not instance.job_id:
            instance.job_id = unique_job_id_generator(instance)
pre_save.connect(pre_save_job_id,sender=Job)


   
    
class JobImage(models.Model):
    job =models.ForeignKey(Job,on_delete=models.CASCADE)
    image =models.ImageField(upload_to='jobs/job_images/',default='jobs/job_images/jobs.jpg',blank=True,null=True)

    @property 
    def photo_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url 
            
    # def __str__(self) -> str:
    #     return super(self.job.title + 'image').__str__()

    

# class Invoice(models.Model):
#     invoice id
#     invoice date
#     invoice due
#     invoice status
#     invoice to_
#     invoice job title
#     invoice application charge

templates/jobs/add_jobs.html
{% extends 'base.html' %}
{% block title %} Add Jobs{%endblock%}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/additional-methods.min.js"></script>

<main id="main">
{% if user.is_authenticated and not user.personal.user_type %}
<br>
<div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
  <strong>Hello {{user.username}} !</strong> <a href="{% url 'profile_form' %}">Click Here </a>  To Complete Your Profile.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
    <!-- ======= Jobs  breadcrumbs Section ======= -->
<br> 
    <section class="breadcrumbs">
    
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Post Jobs</h2>
          <ol>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'jobs' %}">Jobs</a></li>
            <li>Post Jobs</li>
          </ol>
        </div>

      </div>
    </section><!-- Job breadcrumbs Section -->
    <br>
    <section id="add_job" class="add_job bg-light">
 <div class="container ">

        <div class="row">

          <div class="col-md-10 mx-auto">
          <div class="card mb-5 shadow-lg  bg-body rounded">
  {% comment %} <h5 class="card-header text-center py-4">Add Artist's Event</h5> {% endcomment %}
  <div class="card-body">

<form method="POST" enctype="multipart/form-data" id="job">
{% csrf_token %}
{{ myform.media }}
 {{ form|crispy}}
 
  {% if user.is_authenticated and  user.personal.user_type == 'seeker' %}
  
  <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
  <strong>Hello {{user.username}} !</strong> Job Seekers Cannot Post Jobs .To Post Jobs <a href="{% url 'profile_form' %}">Click Here </a> To Change Type Of User. 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
  {% else %}
<div class="d-grid gap-2 col-6 mx-auto">
  <button class="btn btn-primary" >Submit</button>
  {% endif %}
</div>
</form>
</div>
</div>
</div>
</div>
</div>


</section>
  </main><!-- End #main -->
  <script type="text/javascript">
  
    $.validator.addMethod('filesize', function (value, element, param) {
      return this.optional(element)||(element.files[0].size <= param * 1000000)
  }, 'File size must be less than {0}');
  
  jQuery(function ($) {
      "use strict";
      $('#job').validate({
          rules: {
              title : {
                  required: true,
                  minlength: 10
              },
              description : {
                required: true,
                minlength: 30
            },
            application_deadline : {
              required: true,
              
          },
          job_done_date : {
            required: true,
            
        },
        location : {
          required: true,
          minlength: 3
      },
      address : {
        required: true,
        minlength: 3
    },
              image: {
                  required: false,
                  extension: "jpg,jpeg,png",
                  filesize: 5,
              },
              video: {
                required: false,
                extension: "MKV,MP4,AVI,MOV",
                filesize: 10,
            }
          },
          messages: {
            
            title :{
              minlength: 'Title Should Contain A Minimum of 10 Characters'
            },
            tag : 'This field is required',
            description :{
              minlength: 'Description Should Contain 30 Characters'
            },
            application_deadline :{
              minlength: 'Application  Deadline Should Be Greater Than The Current Time ! '
            },
            job_done_date :{
              minlength: 'Time Job To be Done  Should Be Greater Than The Current Time !'
            },
            county :'This field is required',
            location :{
              minlength: 'Location should contain a minimum of 3 characters'
            },
            address:{
              minlength: 'Address should contain a minimum of 3 characters'
            },
            video :{
              filesize:'File size must be less than 10 mb.',
              accept:"Please upload MKV,MP4,AVI,MOV file of notice.",
            },
            image :{
              filesize:'File size must be less than 5 mb.',
              accept:"Please upload .jpg or .png or .jpeg file of notice.",
            
          },
        },
      });
  });

</script>
  {% endblock %}

templates/jobs/job-details.html
{% extends 'base.html' %}
{% block title %} Job-Details{%endblock%}
{% block content %}
{% load static %}
{% load humanize %}
{% load job_tags %}
{% load recent_jobs %}
<main id="main">
{% if user.is_authenticated and not user.personal.user_type %}
<br>
<div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
  <strong>Hello {{user.username}} !</strong> <a href="{% url 'profile_form' %}">Click Here </a>  To Complete Your Profile.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

{% include 'includes/messages.html'%}
    <!-- ======= Jobs  breadcrumbs Section ======= -->
<br> 
    <section class="breadcrumbs">
    
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Job Details</h2>
          <ol>
            <li><a href="{% url 'home' %}">Home</a></li>
             <li><a href="{% url 'jobs' %}">Jobs</a></li>
            <li>Jobs Details</li> 
          </ol>
        </div>

      </div>
    </section><!-- Job breadcrumbs Section -->

    <section id="blog" class="blog">
      <div class="container-fluid" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-9 entries">

            <article class="entry entry-single">
                                  
{% if job.jobimage_set.all %}


<section id="fancy">
  <div class="row">
    <div class="large-5 column">
      <div class="xzoom-container">

              {% for job_image in job.jobimage_set.all %}
              {% if forloop.counter == 1 %}
              {% comment %} <div class="entry-img"> {% endcomment %}
                {% comment %} <img src="{{job_image.image.url}}" alt="{{job.title|truncatechars:10}}" class="img-fluid" height="250"> {% endcomment %}
             
              <img class="xzoom4" id="xzoom-fancy" src="{{job_image.image.url}}" class="img-fluid"  height="450" xoriginal="{{job_image.image.url}}" />
              <br>
            {% comment %} </div> {% endcomment %}
              {% endif %}
              {% comment %} <div class="entry-img"> {% endcomment %}
                {% comment %} <img src="{{job_image.image.url}}" alt="{{job.title|truncatechars:10}}" class="img-fluid" height="250"> {% endcomment %}
              {% comment %} </div> {% endcomment %}

              <div class="xzoom-thumbs d-flex d-inline-flex">
                <a href="{{job_image.image.url}}">
                  <img class="xzoom-gallery4" width="80" src="{{job_image.image.url}}"   alt="{{job.title|truncatechars:10}}">
                </a>
              </div>
          
              {% endfor %}
            </div>
          </div>
          <div class="large-7 column"></div>
        </div>
        </section>
{% endif %}
              
{% comment %} <div class="entry-img">
                <img src="{{job.image.url}}" alt="{{job.title|truncatechars:10}}" class="img-fluid" height="250">
              </div> {% endcomment %}

              <h2 class="entry-title mt-3">
                <a >{{job.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'jobs_by' job.user.username %}">{{job.user.username}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a><time>{{job.created_date }}</time></a></li>
                  <li class="d-flex align-items-center"> 
                  {%if job.status == 'Approved' %}
                  <i class="bi bi-check-circle-fill"> </i> <a>Approved  </a>
                  {% elif job.status == 'Done' %}
                  <i class="bi bi-check-circle-fill"> </i> <a>Done </a>
                  {% else %}
                    <a href="{% url 'this_job_applications' job.slug %}"><span class="badge rounded-pill bg-info text-dark"> {{job.applications.count}}</span>  Applications</a></li>
                  {% endif %}
                              </ul>
              </div>

              <div class="entry-content">
              <div class="card mt-2 shadow  mb-5 bg-body rounded ">
  <div class="card-body">
              <h6><u>Job Description</u> </h6> <p>   {{job.description | safe}} </p>
              </div>
              </div>
                {% comment %} <h6><u>Description :</u> </h6> <p>   {{artist.event_description | safe}} </p> {% endcomment %}
                <div class="card mt-2 shadow  mb-5 bg-body rounded ">
  <div class="card-body">
                <h6><u>Job Tag</u> </h6> <p>  <span class="badge rounded-pill bg-primary"> <a class="link-light" href="{% url 'tags' job.tag.slug %}">{{job.tag}}</a> </span>  </p>
                </div>
              </div>
                <div class="card mt-2 shadow  mb-5 bg-body rounded ">
  <div class="card-body">
                <h6><u>Application Deadline </u> </h6> <p>   {{job.application_deadline}} </p>
                <h6><u>Job To Be Done At </u> </h6> <p>   {{job.job_done_date}} </p>
                </div>
              </div>

                <div class="card mt-2 shadow  mb-5 bg-body rounded ">
  <div class="card-body">
                <h6><u>Job Location </u> </h6> <p>   {{job.county}} ,  {{job.location}}</p>
               
                <h6><u> Job Address </u> </h6> <p>   {{job.address}} </p>
                
                </div>
              </div>
                <div class="card mt-2 shadow  mb-5 bg-body rounded ">
  <div class="card-body">
                <h6><u>Reference No </u> </h6> <p>   {{job.job_id}} </p>
                
                </div>
              </div>
              {% comment %} {% if job.video %}
               <div class="card mt-2 shadow  mb-5 bg-body rounded ">
  <div class="card-body">
  <h6><u>Job Video </u> </h6> 
              <div class="ratio ratio-16x9">
  <video  controls>
  <source src="{{job.video.url}}" type="video/mp4">
  <source src="{{job.video.url}}" type="video/ogg">
  <source src="{{job.video.url}}" type="video/webm">

</video>
</div>
</div>
              </div>
              {% endif %} {% endcomment %}
              
              <div class="d-grid gap-2 d-md-flex justify-content-md-between">

<!--if user has logged in and owns this job then allow user to delete or edit-->

 {% if user.is_authenticated and  user.id == job.user.id %}
  <a class="btn btn-outline-info me-md-2" href="{% url 'update_job' job.slug %}">Edit</a>
   <a class="btn btn-outline-danger me-md-2" href="{% url 'delete_job' job.slug %}">Delete</a>
{% endif %}

<!-- end if user has logged in and owns this job then allow user to delete or edit-->

<!-- if user is a seeker and does not own this job and status of job is not approved or done allow him to apply-->

   {% if not user.is_authenticated %}
  <a href="{% url 'apply_job' job.id %}" class="btn btn-outline-primary" >Apply</a>
  

  {% elif user.is_authenticated and user.personal.user_type == 'seeker' and user.id != job.user.id       and job.status != 'Approved' and job.status != 'Done' %}
  <a href="{% url 'apply_job' job.id %}" class="btn btn-outline-primary" >Apply</a>
  {% endif %}

<!-- end if user is a seeker and does not own this job and status of job is not approved or done allow him to apply-->

<!-- show only when status is approved or done -->
{% if job.status == 'Approved' %}

<a class="btn btn-secondary me-md-2" href="{% url 'this_job_applications' job.slug %}">Has An Approved Application </a>

{% elif job.status == 'Done' %}

<a class="btn btn-secondary me-md-2" href="{% url 'this_job_applications' job.slug %}">Done Job </a>
<!-- end show only when status is approved or done -->

{% else %}

<!-- show number of application to owner-->
{% if user.is_authenticated and  user.id == job.user.id %}

<a class="btn btn-outline-primary me-md-2" href="{% url 'this_job_applications' job.slug %}">View Applications <span class="badge rounded-pill bg-info text-dark">{{job.applications.count}}</span></a>

{% endif%}


<!-- end show number of applicatio to owner-->
</div>
{% endif%}


<!-- if logged in user has not created profile-->
 {% if user.is_authenticated and not user.personal.user_type %}
  
  <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
  <strong>Hello {{user.username}} !</strong>To  Apply This Job  Complete Your Profile First.<a href="{% url 'profile_form' %}" >Complete Profile </a>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

<!-- end if logged in user has not created profile-->

  {% elif user.is_authenticated and user.personal.user_type == 'recruiter' and user.id != job.user.id and job.status != 'Done' %}
  <br>  
  <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
  <strong>Hello {{user.username}} !</strong>  Job Recruiters Cannot Apply For Jobs .To Apply For Jobs <a href="{% url 'edit_profile' user.personal.profile_uuid  %}">Click Here </a> To Change Type Of User. 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>


  {% endif%}
              </div>

            
            </article>
           

          </div><!-- End blog entries list -->

          <div class="col-lg-3">

            <div class="sidebar">

             {% include 'includes/search.html'%}
            

             <h3 class="sidebar-title">Similar Jobs</h3>
              <div class="sidebar-item recent-posts">
              {% comment %} {% get_related_job_by_tag as jobs %} {% endcomment %}
              {% for job in object.get_related_job_by_tag %}
                <div class="post-item clearfix">
                 
                  <h4 class="pt-2"><a href="{{job.get_absolute_url}}">{{job.title|truncatechars:55}}</a></h4>
                  
                </div>
                {% empty %}
                <div class="post-item clearfix">
                 
                  <h4 class="pt-2">No Similar Jobs Found !</h4>
                  
                </div>
                {% endfor %}
               

              </div><!-- End sidebar recent posts-->

              <h3 class="sidebar-title">Tags</h3>
              <div class="sidebar-item tags">
              {% get_tags as tags %}
                <ul> 
                {% for tag in tags%}
                  <li><a href="{{tag.get_absolute_url}}">{{tag.name}}</a></li>
                  {% endfor%}
                 
                </ul>
                
              </div><!-- End sidebar tags-->
            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Single Section -->

    </main>

{% endblock %}